spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.252.128
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 5000ms
  # 连接器客户端配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 集群模式的redis配置
#    cluster:
#      max-redirects: 3
#      nodes: 192.168.0.201:7001,192.168.0.201:7002,192.168.0.201:7003,192.168.0.201:7004,192.168.0.201:7005,192.168.0.201:7006
  # 主从模式的redis配置
#    sentinel:
#      #哨兵监听的 master名称
#      master: mymaster
#      # 哨兵地址列表，多个以,分割
#      nodes: 192.168.0.201:7001,192.168.0.201:7002
#      password: 123456
